apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - helm.yaml

configMapGenerator:
  - name: {{ .app_name }}-base-values
    namespace: nginx
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml