apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: picluster
servers: 1
agents: 2
# Setting version of k3s
image: rancher/k3s:v1.29.6-k3s1
# Setting docker network to be used
network: picluster
options:
  # Disable Load balancer
  k3d:
    disableLoadbalancer: true
  # Extra arguments for k3s
  k3s:
    extraArgs:
      - arg: --tls-san=127.0.0.1
        nodeFilters:
          - server:*
      # Disable traefik, servicelb, flannel and network-policy
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
      - arg: --disable-kube-proxy
        nodeFilters:
          - server:*
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
      # Adding cluster PODs and Services CIDRs
      - arg: --cluster-cidr=10.42.0.0/16
        nodeFilters:
          - server:*
      - arg: --service-cidr=10.43.0.0/16
        nodeFilters:
          - server:*
        # Exposing metrics
      - arg: --kube-controller-manager-arg=bind-address=0.0.0.0
        nodeFilters:
          - server:*
      - arg: --kube-scheduler-arg=bind-address=0.0.0.0
        nodeFilters:
          - server:*
      
