apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx

resources:
  - ../../base

configMapGenerator:
  - name: ingress-nginx-overlay-values
    namespace: nginx
    files:
      - values.yaml=values.yaml