apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ .app_namespace }}

resources:
  - ../../base

configMapGenerator:
  - name: {{ .app_name }}-overlay-values
    files:
      - values.yaml=values.yaml