apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ../../base

configMapGenerator:
  - name: cilium-overlay-values
    files:
      - values.yaml=values.yaml