# nginx application
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-app
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: nginx
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./structure2/platform/nginx/app/overlays/dev
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-config
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: nginx
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress-nginx-app
  path: ./structure2/platform/nginx/config/overlays/prod
  prune: true
  postBuild:
    substitute:
      nginx_load_balancer_ip: "10.0.0.2"
      : "eu-central-1"
    # substituteFrom:
    #   - kind: ConfigMap
    #     name: cluster-vars
    #     # Use this ConfigMap if it exists, but proceed if it doesn't.
    #     optional: true
    #   - kind: Secret
    #     name: cluster-secret-vars
