---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
spec:
  url: https://helm.cilium.io/
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: cilium
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  valuesFrom:
  - kind: ConfigMap
    name: cilium-base-values
  - kind: ConfigMap
    name: cilium-overlay-values
    optional: true