apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm.yaml

configMapGenerator:
  - name: ingress-nginx-base-values
    namespace: nginx
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml