---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ .app_name }}-app
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/{{ .app_name }}/app/overlays/dev
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ .app_name }}-config
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: {{ .app_name }}-app
  path: ./kubernetes/infrastructure/{{ .app_name }}/config/overlays/dev
  prune: true