kind: Kustomization
metadata:
  name: cilium-app
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: nginx
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/cilium/app/overlays/dev
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cilium-config
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: nginx
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cilium-app
  path: ./kubernetes/infrastructure/cilium/config/overlays/dev
  prune: true