# nginx application
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx-app
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: nginx
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/nginx/app/overlays/dev
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx-config
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: nginx
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress-nginx-app
  path: ./kubernetes/infrastructure/nginx/config/overlays/dev
  prune: true
